// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoGSA.App.Persistencia;

namespace ProyectoGSA.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProyectoGSA.App.Dominio.Entidades.Docente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salario")
                        .HasColumnType("float");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Docente");
                });

            modelBuilder.Entity("ProyectoGSA.App.Dominio.Entidades.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("ProyectoGSA.App.Dominio.Entidades.Acudiente", b =>
                {
                    b.HasBaseType("ProyectoGSA.App.Dominio.Entidades.Persona");

                    b.Property<int?>("acudidoid")
                        .HasColumnType("int");

                    b.HasIndex("acudidoid");

                    b.HasDiscriminator().HasValue("Acudiente");
                });

            modelBuilder.Entity("ProyectoGSA.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.HasBaseType("ProyectoGSA.App.Dominio.Entidades.Persona");

                    b.Property<int?>("madreid")
                        .HasColumnType("int");

                    b.Property<string>("nacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("padreid")
                        .HasColumnType("int");

                    b.HasIndex("madreid");

                    b.HasIndex("padreid");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("ProyectoGSA.App.Dominio.Entidades.Acudiente", b =>
                {
                    b.HasOne("ProyectoGSA.App.Dominio.Entidades.Estudiante", "acudido")
                        .WithMany()
                        .HasForeignKey("acudidoid");

                    b.Navigation("acudido");
                });

            modelBuilder.Entity("ProyectoGSA.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.HasOne("ProyectoGSA.App.Dominio.Entidades.Persona", "madre")
                        .WithMany()
                        .HasForeignKey("madreid");

                    b.HasOne("ProyectoGSA.App.Dominio.Entidades.Persona", "padre")
                        .WithMany()
                        .HasForeignKey("padreid");

                    b.Navigation("madre");

                    b.Navigation("padre");
                });
#pragma warning restore 612, 618
        }
    }
}
